# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161112_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
        migrations.AddField(
            model_name='atentionqueue',
            name='current_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
