# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20161112_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='atentionqueue',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
