# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20161112_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atentionqueue',
            name='average_attention_time',
            field=models.PositiveIntegerField(default=600),
        ),
    ]
