# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20161122_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_queue',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='backend.AtentionQueue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atentionqueue',
            name='specialty',
            field=models.CharField(choices=[('1', 'Clínica'), ('2', 'Pediatría'), ('3', 'Odontología'), ('4', 'Cirujía'), ('5', 'Traumatología'), ('6', 'Oftalmología')], max_length=1),
        ),
    ]
