# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20161123_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='backend.AtentionQueue'),
        ),
    ]
