# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20161123_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='current_queue',
        ),
        migrations.AddField(
            model_name='patient',
            name='queue',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='backend.AtentionQueue'),
            preserve_default=False,
        ),
    ]
