# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20161123_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.HealthCenter')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('waitTime', models.PositiveIntegerField(default=0)),
                ('travelTime', models.PositiveIntegerField(default=0)),
                ('patientsWaiting', models.PositiveIntegerField(default=0)),
                ('distance', models.PositiveIntegerField(default=0)),
                ('ranking', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='start_time',
            new_name='startTime',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='triage_scale',
            new_name='triageScale',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='waittime',
            new_name='waitTime',
        ),
        migrations.AddField(
            model_name='attentionhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Patient'),
        ),
        migrations.AddField(
            model_name='attentionhistory',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AtentionQueue'),
        ),
        migrations.AddField(
            model_name='attentionhistory',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DeleteReason'),
        ),
    ]
