# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20161127_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('waitTime', models.PositiveIntegerField(default=0)),
                ('health_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.HealthCenter')),
            ],
            options={
                'verbose_name_plural': 'Atention records',
            },
        ),
        migrations.CreateModel(
            name='TriageScaleLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
                ('max_wait_in_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='attentionhistory',
            name='health_center',
        ),
        migrations.RemoveField(
            model_name='attentionhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='attentionhistory',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='attentionhistory',
            name='reason',
        ),
        migrations.AlterField(
            model_name='patient',
            name='triageScale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TriageScaleLevel'),
        ),
        migrations.DeleteModel(
            name='AttentionHistory',
        ),
        migrations.AddField(
            model_name='attentionrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Patient'),
        ),
        migrations.AddField(
            model_name='attentionrecord',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AtentionQueue'),
        ),
        migrations.AddField(
            model_name='attentionrecord',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DeleteReason'),
        ),
        migrations.AddField(
            model_name='attentionrecord',
            name='triaceScale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TriageScaleLevel'),
        ),
    ]
