# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20161201_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcenter',
            name='ranking',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
