# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_healthcenter_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atentionqueue',
            name='current_size',
        ),
        migrations.AlterField(
            model_name='patient',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='backend.AtentionQueue'),
        ),
    ]
