# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20161204_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='waitTime',
        ),
    ]
