# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_patient_waittime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attentionrecord',
            old_name='triaceScale',
            new_name='triageScale',
        ),
        migrations.AddField(
            model_name='recommendationdata',
            name='sector',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
