# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20161204_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='backend.AtentionQueue'),
        ),
    ]
