# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20161204_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='ranking',
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
