# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20161204_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atentionqueue',
            name='average_attention_time',
        ),
        migrations.AddField(
            model_name='atentionqueue',
            name='atention_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atentionqueue',
            name='atention_time_total',
            field=models.IntegerField(default=0),
        ),
    ]
