# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20161208_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='atentionqueue',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
