# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_reports_upcomingpatientfeedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingpatientfeedmessage',
            name='message_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
